feat: add support for custom principal iam arns
philips-labs/terraform-aws-github-oidc pull request #49
Opened 2022-10-10 17:41 UTC by SushiFu

2022-10-18 21:30 UTC, npalm reviewed
Thanks for your contribution. Will run a quick test in the next days

2022-10-18 21:35 UTC, npalm requested changes
Looks good, a small remark. I think we can directly use the array in the policy. @GuptaNavdeep1983 I think this is a better approach as the hard coded root principal we have. What do you think?

2022-10-26 23:32 UTC, SushiFu commented on main.tf
> +        identifiers = [statement.value]
Agreed I have refactored to have only one statement for AWS principals

2022-10-27 10:56 UTC, GuptaNavdeep1983 approved these changes

2022-10-27 12:12 UTC, npalm reviewed
Thanks, change looks good. Need to run a quick deployment test

2022-10-28 07:31 UTC, npalm approved these changes

2022-10-28 07:32 UTC, merged